{% set name = "hdbpp-cm" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/hdbpp/hdbpp-cm/-/archive/{{ version }}/hdbpp-cm-{{ version }}.tar.gz
  sha256: 134e0bf1a24b7b694a69f1bcc9abf15388eb91e530974590344bf65a1ffa928b

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango <9.4
    - omniorb
    - omniorb-libs

test:
  commands:
    - hdb++cm-srv --help 2>&1 | grep usage

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango device server for the HDB++ Configuration Manager
  dev_url: https://gitlab.com/tango-controls/hdbpp/hdbpp-cm
  doc_url: https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/archiving/HDB++.html

extra:
  recipe-maintainers:
    - beenje
