{% set name = "hdbpp-cm" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/hdbpp/hdbpp-cm/-/archive/{{ version }}/hdbpp-cm-{{ version }}.tar.gz
  sha256: b6c8bafbacfe43045b9bd7939514061e3316d4abbc984cc48760272c01e63aa4

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango
    - omniorb-libs

test:
  commands:
    - hdb++cm-srv --help 2>&1 | grep usage

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango device server for the HDB++ Configuration Manager
  dev_url: https://gitlab.com/tango-controls/hdbpp/hdbpp-cm
  doc_url: https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/archiving/HDB++.html

extra:
  recipe-maintainers:
    - beenje
